{{- if .Values.ingresses.enabled }}

{{- if not (eq (len .Values.ingresses.hostnames) (.Values.replicaCount | int))}}
{{- fail "ingresses.hostnames must be the same length as replicaCount"}}
{{- end }}

{{- if and (not (eq (len .Values.ingresses.tlsSecrets) 0)) (not (eq (len .Values.ingresses.hostnames) (len .Values.ingresses.tlsSecrets | int))) }}
{{- fail "ingresses.hostnames must be the same length as ingresses.tlsSecrets"}}
{{- end }}

{{- range $index, $hostname := $.Values.ingresses.hostnames }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ocspd.fullname" $ }}-{{ $index | toString }}
  labels:
    {{- include "ocspd.labels" $ | nindent 4 }}
  {{- with $.Values.ingresses.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $.Values.ingresses.className }}
  rules:
    - host: {{ $hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ocspd.fullname" $ }}-{{ $index | toString }}
                port:
                  name: http
  {{- if $.Values.ingresses.tlsSecrets }}
  tls:
    - hosts:
        - {{ $hostname }}
      secretName: {{ index $.Values.ingresses.tlsSecrets $index }}
  {{- end }}
---
{{- end }}
{{- end }}